server:
  port: 8084
spring:
  application:
    name: product-service
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: product_service
eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
